# <mark style="display:block; background:#d1c4e9; color:#1a1a1a; padding:6px 12px; border-radius:4px">2주차 · 취향이 비슷한 사람끼리 묶는다</mark>

지난 시간에는 가장 많이 담긴 종목 10개를 300명 모두에게 똑같이 보여 주었습니다.

점수는 0.2163이 나왔고, 알고리즘을 하나도 쓰지 않은 것 치고는 나쁘지 않았습니다.

그런데 마지막에 문제를 하나 보았습니다.

원금을 지키는 것이 최우선인 투자자와 레버리지 상품까지 담는 투자자에게, 우리는 **같은 근거로 만든 같은 목록**을 내밀었습니다.

오늘은 이 문제를 풉니다.

그 사람이 지금까지 담아 온 것을 보고 취향을 짐작해서, 사람마다 다른 목록을 만듭니다.

그리고 추천을 채점하는 방법이 하나가 아니라는 것을 알아보고, 세 가지 지표를 직접 계산해 봅니다.

---

### 오늘의 구성

| 파트 | 종류 | 어디서 | 하는 일 |
|---|---|---|---|
| 1 | 개념 | 슬라이드 | 지난 시간의 한계를 다시 보고, 무엇이 더 필요한지 정리합니다 |
| 2 | 실습 | **이 노트북 2.2~2.8** | 거래 기록에서 주력 섹터와 평균 위험도를 뽑아 사람을 묶습니다 |
| 3 | 개념 | 슬라이드 | 채점하는 방법 세 가지를 배웁니다 |
| 4 | 실습 | **이 노트북 4.2~4.4** | 세 지표를 직접 계산하고 1주차와 비교합니다 |

이 노트북은 **실습 두 파트**만 담고 있습니다. 그래서 절 번호가 `2.` 부터 시작합니다.
개념 두 파트는 슬라이드로 진행합니다.

### 강사용 · 예상 소요 시간

- 전체 셀을 처음부터 끝까지 실행 — **약 12초**
- 가장 오래 걸리는 셀은 마지막 비교 셀로 약 6초입니다.
- 첫 셀의 `import` 가 3~5초 걸리므로 **수업 시작 전에 미리 한 번 실행**해 두시길 권합니다.

## <mark style="display:block; background:#c8e6c9; color:#1a1a1a; padding:6px 12px; border-radius:4px">시작하기 · 이 노트북을 여는 법</mark>

이 노트북은 **아무것도 설치하지 않고** 브라우저에서 바로 실행할 수 있습니다.

데이터도 따로 내려받지 않습니다. 아래 준비 셀이 알아서 가져옵니다.

### Google Colab 으로 열기

1. 아래 주소를 눌러 주세요.
   - https://colab.research.google.com/github/welovecherry/recsys/blob/main/notebooks/02_rules_metrics.ipynb
2. 구글 계정으로 로그인합니다.
   - 이미 로그인돼 있으면 이 단계는 그냥 지나갑니다.
3. **경고창이 뜨면 `Run anyway` 를 누릅니다.**
   - `Warning: This notebook was not authored by Google` 이라는 문구가 나옵니다.
   - 강사가 만든 파일이니 **`Run anyway`(그래도 실행)** 를 누르시면 됩니다.
4. **아래 "실습 준비" 셀의 ▶ 버튼을 누릅니다.**
   - 실습에 필요한 자료를 받아옵니다. 10초쯤 걸립니다.
   - "준비 끝" 이 나오면 성공입니다.
5. 그다음부터는 위에서 아래로 셀을 하나씩 실행하면 됩니다.

> ⚠ **고친 내용을 남기려면** 메뉴에서 `파일 → 드라이브에 사본 저장` 을 눌러 주세요.
> 누르지 않으면 탭을 닫을 때 사라집니다.

---

### <mark style="display:block; background:#c8e6c9; color:#1a1a1a; padding:6px 12px; border-radius:4px">먼저 이 셀부터 실행하세요  ▶</mark>

In [1]:
# 이 셀의 목적 — Colab 이면 실습 자료를 받아온다.
# 내 컴퓨터에서 열었다면 아무 일도 하지 않고 넘어갑니다.
import os          # 폴더를 만들고 옮겨 다니는 도구
import sys         # 지금 파이썬이 어떤 환경인지 알려 주는 도구
import subprocess  # 터미널 명령을 파이썬에서 대신 실행해 주는 도구

if "google.colab" in sys.modules:                    # Colab 이면 이 안이 실행된다
    if os.path.exists("/content/recsys"):            # 전에 받아 둔 것이 있으면 최신으로
        subprocess.run(["git", "-C", "/content/recsys", "pull", "-q", "--ff-only"])
    else:                                            # 처음이면 통째로 내려받는다
        subprocess.run(["git", "clone", "-q",
                        "https://github.com/welovecherry/recsys.git", "/content/recsys"])
    os.chdir("/content/recsys/notebooks")            # 노트북 폴더 안으로 이동
    print("준비 끝 —", os.getcwd(), "· 아래 셀부터 차례로 실행하세요.")
else:
    print("내 컴퓨터에서 실행 중입니다 —", os.getcwd(), "· 따로 받아올 것이 없습니다.")

내 컴퓨터에서 실행 중입니다 — /Users/hong/workspaces/org_physical-spark/course-recsys/notebooks · 따로 받아올 것이 없습니다.

## <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2 · 실습 — 사람을 무리로 묶는다</mark>

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2.1 오늘 나오는 말  `[PPT]`</mark>

1. **섹터 (sector)** — 종목이 속한 산업 분야
   - 반도체 · 배당 · 채권 · 레버리지처럼 성격이 비슷한 종목을 묶은 이름입니다.
   - `items.csv` 의 `sector` 칸에 들어 있습니다.
2. **위험도 (risk_level)** — 그 종목이 얼마나 크게 오르내리는지를 1~5로 매긴 숫자
   - 1은 국채처럼 잘 안 움직이는 것, 5는 레버리지처럼 크게 흔들리는 것입니다.
   - `items.csv` 의 `risk_level` 칸에 들어 있습니다.
3. **세그먼트 (segment)** — 취향이 비슷하다고 판단한 사람들의 묶음
   - 실무에서 **사용자 세그먼테이션**이라고 부르는 그 작업입니다.
   - 아래 코드에서는 우리말로 `무리` 라고 적었습니다. 같은 말입니다.
   - 오늘은 `주력섹터|평균위험도` 형태의 문자열을 무리 이름으로 씁니다.
   - 같은 이름을 가진 사람들이 한 무리입니다.
   - **`|` 는 파이프(pipe)** 라고 부르는 구분 기호입니다. 뜻은 없고 두 값을 한 덩어리로 잇기만 합니다.
   - `레버리지|4` 는 소리 내어 읽을 때 **「레버리지 사」** 라고 읽습니다. 세로줄은 읽지 않습니다.
   - 왜 굳이 잇나 — **딕셔너리에서 찾으려면 값이 하나여야** 합니다. 섹터와 위험도를 따로 들고 다니면 짝을 맞추기가 번거롭습니다.
4. **피처 (feature)** — 사람이나 상품을 설명하려고 데이터에서 뽑아낸 값
   - 오늘 만드는 **주력 섹터**와 **평균 위험도**가 바로 피처입니다.
   - 이 피처 두 개로 세그먼트를 나눕니다.
5. **매핑 (mapping)** — 어떤 값을 다른 값으로 바꿔 주는 것
   - 종목 번호 `I044` 를 넣으면 섹터 `반도체` 가 나오게 하는 일입니다.
   - 지난 시간에 만든 "번호 → 이름" 딕셔너리와 같은 원리입니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2.2 준비 — 지난 시간 것을 다시 불러온다</mark>

**2.2 에서 하는 일** — 지난 시간에 만든 것을 그대로 다시 만듭니다. 오늘 점수를 지난주와 비교하려면 출발점이 같아야 합니다.

**1. 무엇을 다시 만드나**
- 표 세 개(종목·투자자·거래 기록)를 읽고, **시간 순서로** 학습 구간과 채점 구간으로 나눕니다.
- 「번호 → 이름」 딕셔너리와, 사람마다 **이미 담은 종목** 집합을 만듭니다.
- 1주차 추천 방식(모두에게 같은 인기 순위)과 그 점수 **Recall@10 = 0.2163** 을 되살립니다.

**2. 왜 시간으로 나누나**
- 마지막 한 달을 가려 두고 앞 기간만 보고 추천합니다. 가려 둔 한 달이 **정답**입니다.
- 무작위로 나누면 미래를 보고 맞히는 셈이 됩니다. 이 이야기는 3주차에 제대로 다룹니다.

**3. 설명 없이 한 번에 실행합니다** — 지난 시간에 이미 한 것이라 오늘은 결과만 확인합니다.

> ⚠ `users.csv` 에는 사실 투자 성향이 적혀 있습니다. 그런데 **오늘 그것을 쓰지 않습니다.**
> 그 값은 이 연습용 데이터를 만들 때 심어 둔 정답지라서, 쓰면 답을 보고 문제를 푸는 셈이 됩니다.
> 오늘은 **거래 기록만** 보고 사람을 알아냅니다.

In [2]:
# 준비 — 필요한 도구를 불러옵니다.
import sys                                  # 파이썬이 파일을 찾는 경로를 다루는 도구

sys.path.insert(0, ".")                     # 지금 폴더에서 recsys.py 를 찾게 한다
sys.path.insert(0, "notebooks")             # 한 칸 안쪽 폴더도 찾게 한다

import pandas as pd                         # 표를 다루는 도구. 앞으로 pd 라고 부른다
import numpy as np                          # 숫자 계산 도구. 앞으로 np 라고 부른다
import recsys                               # 이 수업용으로 만든 도구 모음

print("도구 준비 완료 · pandas", pd.__version__, "· numpy", np.__version__)

도구 준비 완료 · pandas 3.0.5 · numpy 2.5.2

**결과 읽는 법**

- `도구 준비 완료` 는 도구를 문제없이 불러왔다는 표시입니다.
  - `pandas 3.0.5` · `numpy 2.5.2` 는 설치된 도구의 버전 번호입니다.
  - 버전 숫자가 조금 달라도 실습에는 지장이 없습니다.

In [3]:
# 데이터를 읽고 시간으로 나눕니다. 지난 시간과 똑같습니다.
items, users, interactions = recsys.load()                  # 종목·투자자·거래 기록 세 표를 한 번에 읽는다
print(f"종목 {len(items)}개 · 투자자 {len(users)}명 · 거래 기록 {len(interactions):,}건")

train, test, 기준시점 = recsys.split_by_time(interactions)   # 앞 11개월 / 마지막 1개월 / 자른 날짜
print(f"{기준시점.date()} 기준 · 학습 {len(train):,}건 · 채점 {len(test):,}건")

# 종목 번호를 이름으로 바꿔 주는 딕셔너리 (지난 시간에 만든 것)
종목표_번호색인 = items.set_index("item_id")          # 종목 번호를 행 이름으로 세운다
name_of = 종목표_번호색인["name"].to_dict()           # {번호: 이름} 딕셔너리으로 바꾼다
print("이름 딕셔너리 :  I044 →", name_of["I044"])


def 번호를_이름으로(번호목록):
    """종목 번호 목록을 사람이 읽는 이름 목록으로 바꿔 돌려준다."""
    이름목록 = []                                     # 담을 빈 목록
    for 번호 in 번호목록:                              # 번호를 하나씩 꺼내서
        이름목록.append(name_of[번호])                 # 딕셔너리에서 이름을 찾아 담는다
    return 이름목록                                   # 이름만 든 목록을 돌려준다


print("함수 확인   :", 번호를_이름으로(["I044", "I079"]))   # 만든 함수를 바로 써 본다

# 사람마다 학습 구간에서 이미 담은 종목들
사람별_담은종목 = train.groupby("user_id")["item_id"].apply(set)   # 사람별로 묶어 종목을 집합으로
seen_map = 사람별_담은종목.to_dict()                  # {사람: 담은 종목 집합} 딕셔너리
print(f"이미 담은 것 딕셔너리 {len(seen_map)}명 ·  U0003 은 {len(seen_map['U0003'])}건")

# 지난 시간의 추천 방식 — 누가 오든 인기 순위표 위에서부터 10개
종목별_거래건수 = train["item_id"].value_counts()     # 종목마다 기록이 몇 줄인지 센다(많은 순)
인기순위 = list(종목별_거래건수.index)                 # 번호만 많은 순으로 뽑아 목록으로
print("인기 1위    :", name_of[인기순위[0]], f"({종목별_거래건수.iloc[0]}건)")


def 모두에게_같은_추천(user_id, seen):
    """누구에게나 같은 인기 순위표에서 아직 안 담은 것 10개를 준다."""
    return recsys.take(인기순위, seen)                # seen(이미 담은 것)을 빼고 위에서 10개


지난시간_점수, 채점한_사람_수 = recsys.recall_at_k(모두에게_같은_추천, train, test)   # 점수와 채점 인원
print(f"지난 시간 방식  Recall@10 = {지난시간_점수:.4f}  (채점한 사람 {채점한_사람_수}명)")

종목 100개 · 투자자 300명 · 거래 기록 8,086건
2026-07-30 기준 · 학습 7,095건 · 채점 991건
이름 딕셔너리 :  I044 → 삼성전자
함수 확인   : ['삼성전자', 'KODEX 레버리지']
이미 담은 것 딕셔너리 285명 ·  U0003 은 29건
인기 1위    : iShares Core MSCI EAFE ETF (228건)
지난 시간 방식  Recall@10 = 0.2163  (채점한 사람 266명)

**결과 읽는 법**

- 첫 두 줄은 데이터의 크기와 나눈 결과입니다.
  - 종목 100개 · 투자자 300명 · 거래 기록 8,086건을 읽었습니다.
  - `2026-07-30` 을 기준으로 앞은 학습 구간 7,095건, 뒤는 채점 구간 991건입니다.
- `이름 딕셔너리` · `함수 확인` 줄은 「번호 → 이름」 딕셔너리가 제대로 동작하는지 보여 줍니다.
  - `I044` 를 넣으면 `삼성전자` 가 나옵니다.
- `이미 담은 것 딕셔너리 285명` 은 학습 구간에 기록이 있는 사람 수입니다.
  - `U0003 은 29건` 은 U0003 이 학습 구간에 담은 서로 다른 종목이 29개라는 뜻입니다.
- `인기 1위` 는 학습 구간에서 기록이 가장 많은 종목입니다.
  - iShares Core MSCI EAFE ETF 가 228건으로 1위입니다.
- 마지막 줄은 1주차 방식의 점수입니다.
  - Recall@10 = 0.2163 이고, 채점한 사람은 266명입니다.
  - 지난 시간과 같은 값이 나오면 출발점이 같다는 확인이 됩니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2.3 거래 기록에 종목 정보를 붙인다</mark>

**2.3 에서 하는 일** — 「번호 → 섹터」와 「번호 → 위험도」 딕셔너리를 만들고, 그것으로 거래 기록에 섹터 열을 붙입니다.

**1. 왜 붙여야 하나**
- 거래 기록 한 줄에는 `I079` 처럼 **종목 번호만** 있습니다. 번호만으로는 그 종목의 성격을 알 수 없습니다.
- 섹터와 위험도는 **종목 표**(`items.csv`)에 있습니다. 번호를 열쇠로 그 값을 가져와야 합니다.

**2. 딕셔너리를 두 개 만듭니다**
- 지난 시간에 「번호 → 이름」 딕셔너리를 만든 것과 **똑같은 방법**입니다.
- `섹터_사전["I079"]` → `레버리지` · `위험도_사전["I079"]` → `5`

**3. 이 동작의 공식 용어가 매핑(mapping)** 입니다 — 어떤 값을 넣으면 다른 값이 나오게 하는 것.

In [4]:
# 섹터 딕셔너리 — 종목 번호를 넣으면 섹터가 나옵니다.

# 데이터프레임(DataFrame) = 세로줄이 여러 개인 표
# 시리즈(Series) = 세로줄이 하나뿐인 것
섹터_열 = 종목표_번호색인["sector"]        # DataFrame 에서 열 하나만 → Series
섹터_사전 = 섹터_열.to_dict()              # Series → dict. {번호: 섹터}
print(f"섹터 딕셔너리 {len(섹터_사전)}개 ·  I044 → {섹터_사전['I044']}")

# 위험도 딕셔너리 — 같은 방법으로 하나 더
위험도_열 = 종목표_번호색인["risk_level"]   # 위험도 열만 꺼낸다
위험도_사전 = 위험도_열.to_dict()           # {번호: 1~5 숫자}
print(f"위험도 딕셔너리 {len(위험도_사전)}개 ·  I044 → {위험도_사전['I044']}")

# 딕셔너리 두 개를 같이 쓰면 종목 하나를 다 설명할 수 있습니다.
print()
print("I044 →", name_of["I044"], "· 섹터", 섹터_사전["I044"], "· 위험도", 위험도_사전["I044"])
print("I079 →", name_of["I079"], "· 섹터", 섹터_사전["I079"], "· 위험도", 위험도_사전["I079"])

섹터 딕셔너리 100개 ·  I044 → 반도체
위험도 딕셔너리 100개 ·  I044 → 3

I044 → 삼성전자 · 섹터 반도체 · 위험도 3
I079 → KODEX 레버리지 · 섹터 레버리지 · 위험도 5

**결과 읽는 법**

- `섹터 딕셔너리 100개` · `위험도 딕셔너리 100개` 는 딕셔너리에 든 종목 수입니다.
  - 종목 100개가 모두 들어갔다는 뜻입니다.
- 아래 두 줄은 딕셔너리 세 개를 함께 써서 종목 하나를 설명한 것입니다.
  - `I044` 는 삼성전자이고, 섹터는 반도체, 위험도는 3입니다.
  - `I079` 는 KODEX 레버리지이고, 섹터는 레버리지, 위험도는 5입니다.

**4. 거래 기록에 섹터 열을 붙입니다 (3단계)**

1. 거래 기록에서 **종목 번호 열**만 꺼냅니다 (7,095줄).
2. `.map(섹터_사전)` 으로 번호를 섹터로 **갈아 끼웁니다** — `I044` 가 들어가면 `반도체` 가 나옵니다.
3. `.assign(sector=...)` 으로 그 열을 **더한 새 표**를 만듭니다. 원래 표는 그대로 남습니다.

이제 거래 기록 한 줄만 봐도 그게 어느 산업 분야인지 알 수 있습니다.

In [5]:
# 1단계 — 거래 기록에서 종목 번호 열을 꺼냅니다.
거래_종목번호 = train["item_id"]              # 학습 구간 전체의 번호 목록
print(f"1단계 · 번호 {len(거래_종목번호):,}줄 :", list(거래_종목번호.head(3)))

# 2단계 — 각 번호를 섹터 이름으로 바꿉니다.
거래_섹터 = 거래_종목번호.map(섹터_사전)       # map = 딕셔너리를 대고 값을 갈아 끼운다
print("2단계 · 섹터로 바꿈    :", list(거래_섹터.head(3)))

# 3단계 — 원래 표에 그 열을 붙인 새 표를 만듭니다.
거래_섹터포함 = train.assign(sector=거래_섹터)  # assign = 열을 더한 새 표를 돌려준다
print("3단계 · 표의 열 이름   :", list(거래_섹터포함.columns))
print()
거래_섹터포함.head()

1단계 · 번호 7,095줄 : ['I043', 'I032', 'I008']
2단계 · 섹터로 바꿈    : ['지수', '금융', '채권']
3단계 · 표의 열 이름   : ['user_id', 'item_id', 'ts', 'event', 'sector']

  user_id item_id                  ts event sector
0   U0245    I043 2025-08-31 10:00:00  view     지수
1   U0055    I032 2025-09-03 12:00:00  like     금융
2   U0055    I008 2025-09-04 11:00:00  view     채권
3   U0198    I084 2025-09-09 15:00:00  view   레버리지
4   U0198    I090 2025-09-10 00:00:00  like    친환경

**결과 읽는 법**

- `1단계` 줄은 학습 구간의 종목 번호 7,095줄 중 앞 3개입니다.
  - `I043` · `I032` · `I008` 입니다.
- `2단계` 줄은 같은 3개를 섹터로 바꾼 결과입니다.
  - 순서대로 `지수` · `금융` · `채권` 입니다.
- `3단계` 줄은 새 표의 열 이름입니다.
  - 원래 네 열 뒤에 `sector` 열이 하나 더 붙었습니다.
- 아래 표는 새 표의 앞 5줄입니다.
  - 각 줄의 `sector` 칸에 그 종목의 섹터가 들어 있습니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2.4 사람마다 주력 섹터를 찾는다</mark>

**2.4 에서 하는 일** — 사람별로 묶어, 각자 **가장 많이 담은 섹터** 하나를 골라 냅니다.

**1. 왜 「가장 많이」인가**
- 한 사람이 여러 섹터를 담습니다. U0003 은 레버리지 5번, 지수 4번, 반도체 3번입니다.
- 그중 **최다인 하나**로 그 사람을 대표합니다. 거칠지만 규칙 기반 추천은 이렇게 시작합니다.

**2. 어떻게 묶나**
- `groupby("user_id")` 는 **같은 사람의 줄끼리 모아라**는 뜻입니다. 285명이니 묶음이 285개 나옵니다.
- 묶음마다 섹터 목록을 세어 최다를 뽑습니다. 세는 것은 `value_counts()` 가 해 줍니다.

In [6]:
def 가장_많은_값(값들):
    """여러 값 중 가장 자주 나온 것 하나를 돌려준다."""
    센_결과 = 값들.value_counts()   # 값별로 몇 번 나왔는지 세고 많은 순으로 정렬

    #    센_결과 는 이미 많은 순으로 정렬돼 있습니다. 이름은 .index 에 들어 있습니다.
    몇번째 = 0        # 0번째 = 가장 많은 것. 많은 순으로 정렬돼 있기 때문

    return 센_결과.index[몇번째]     # index = 값의 이름 쪽. [0] 이면 가장 많은 것


print("함수 확인 :", 가장_많은_값(pd.Series(["금융", "금융", "지수"])))   # 금융이 나와야 맞다

# 사람별로 묶어서 섹터 열에 위 함수를 적용합니다.
사람별_묶음 = 거래_섹터포함.groupby("user_id")   # 같은 사람의 줄끼리 모은다
print("묶음 개수 :", 사람별_묶음.ngroups, "명")

사람별_섹터목록 = 사람별_묶음["sector"]          # 그 사람이 담은 섹터들만 본다
주력섹터_시리즈 = 사람별_섹터목록.agg(가장_많은_값)   # agg = 묶음마다 위 함수를 한 번씩
print("주력 섹터를 구한 사람 :", len(주력섹터_시리즈), "명")

주력섹터 = 주력섹터_시리즈.to_dict()             # {사람: 주력 섹터} 딕셔너리
print("U0001 →", 주력섹터["U0001"], "·  U0003 →", 주력섹터["U0003"])

함수 확인 : 금융
묶음 개수 : 285 명
주력 섹터를 구한 사람 : 285 명
U0001 → 금융 ·  U0003 → 레버리지

**결과 읽는 법**

- `함수 확인 : 금융` 은 `["금융", "금융", "지수"]` 에서 가장 자주 나온 값입니다.
  - 함수가 의도대로 동작한다는 확인입니다.
- `묶음 개수 : 285 명` 은 사람별로 묶은 묶음의 수입니다.
  - 학습 구간에 기록이 있는 사람 수와 같습니다.
- `주력 섹터를 구한 사람 : 285 명` 은 285명 모두 주력 섹터가 정해졌다는 뜻입니다.
- 마지막 줄은 두 사람의 주력 섹터입니다.
  - U0001 은 `금융`, U0003 은 `레버리지` 입니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2.5 평균 위험도를 구해 무리 이름을 만든다</mark>

**2.5 에서 하는 일** — 사람마다 평균 위험도를 구하고, 주력 섹터와 합쳐 **무리 이름**을 만듭니다.

**1. 왜 위험도까지 필요한가**
- 섹터만으로는 구분이 **거칩니다.**
- 같은 `지수` 섹터를 담더라도, 안전한 지수 ETF만 담는 사람과 레버리지까지 담는 사람은 성향이 다릅니다.
- 그래서 그 사람이 담은 종목들의 **위험도 평균**을 하나 더 씁니다.

**2. 평균 위험도 구하기 (3단계)**
1. 2.3 에서 섹터를 붙인 것과 **똑같은 방법**으로, 이번엔 위험도 숫자를 붙입니다.
2. 사람별로 묶어 **평균**을 냅니다 → U0001 은 **2.75**
3. **소수점을 없앱니다** → 2.75 는 `3`, 4.00 은 `4`

**3. 왜 반올림하나**
- 2.75 와 2.81 을 다른 무리로 보면 **사람마다 무리가 하나씩** 생겨 버립니다.
- 정수로 뭉뚱그려야 비슷한 사람끼리 같은 칸에 모입니다.

In [7]:
# 1단계 — 종목 번호를 위험도 숫자로 바꾼 열을 붙입니다.
거래_위험도 = train["item_id"].map(위험도_사전)        # 번호 → 1~5 숫자로 갈아 끼운다
거래_위험도포함 = train.assign(risk=거래_위험도)       # risk 라는 열을 더한 새 표
print("1단계 · 위험도로 바꿈 :", list(거래_위험도.head(5)))

# 2단계 — 사람별로 묶어 평균을 냅니다.
사람별_위험도 = 거래_위험도포함.groupby("user_id")["risk"]   # 사람별 위험도 묶음
평균위험도_실수 = 사람별_위험도.mean()                 # 묶음마다 평균. 2.75 같은 소수가 나온다
print(f"2단계 · 평균 (소수)  :  U0001 {평균위험도_실수['U0001']:.2f} · U0003 {평균위험도_실수['U0003']:.2f}")

# 3단계 — 반올림해서 정수로 만듭니다. 2.75 나 3.2 를 모두 3 으로 모읍니다.
평균위험도_반올림 = 평균위험도_실수.round(0)           # 2.75 → 3.0
평균위험도_정수 = 평균위험도_반올림.astype(int)        # 3.0 → 3 (소수점 없애기)
평균위험도 = 평균위험도_정수.to_dict()                 # {사람: 1~5 정수} 딕셔너리
print(f"3단계 · 반올림 (정수):  U0001 {평균위험도['U0001']} · U0003 {평균위험도['U0003']}")

1단계 · 위험도로 바꿈 : [3, 3, 2, 5, 4]
2단계 · 평균 (소수)  :  U0001 2.75 · U0003 4.00
3단계 · 반올림 (정수):  U0001 3 · U0003 4

**결과 읽는 법**

- `1단계` 줄은 거래 기록 앞 5줄의 종목 번호를 위험도 숫자로 바꾼 값입니다.
  - `[3, 3, 2, 5, 4]` 는 각 종목의 위험도(1~5)입니다.
- `2단계` 줄은 사람별 평균 위험도(소수)입니다.
  - U0001 은 2.75, U0003 은 4.00 입니다.
- `3단계` 줄은 그 평균을 반올림한 정수입니다.
  - U0001 은 3, U0003 은 4 입니다.
  - 이 정수가 무리 이름의 뒷부분이 됩니다.

**4. 무리 이름 만들기**

```python
무리[사람] = f"{섹터}|{위험도}"      # 예: "금융|3"
```

주력 섹터와 평균 위험도를 **파이프(`|`)로 이어 붙인 문자열**이 그 사람의 무리 이름입니다.
`|` 는 뜻이 없는 구분 기호이고, `레버리지|4` 는 **「레버리지 사」** 라고 읽습니다.

- U0001 → `금융|3`
- U0003 → `레버리지|4`

**5. 결과** — 285명이 **15개 세그먼트**로 나뉩니다. 같은 이름을 가진 사람끼리 한 무리이고, 2.7 에서 무리별로 다른 추천 목록을 만듭니다.

In [8]:
무리 = {}                                # 빈 딕셔너리를 하나 만들어 두고 채운다

for 사람 in 주력섹터:                      # 285명을 한 명씩 돈다
    섹터 = 주력섹터[사람]                  # 그 사람의 주력 섹터
    위험도 = 평균위험도[사람]              # 그 사람의 평균 위험도
    무리[사람] = f"{섹터}|{위험도}"        # 둘을 파이프(|)로 이어 이름 하나로 만든다 — "레버리지|4"

print(f"이름을 붙인 사람 {len(무리)}명 ·  U0001 → {무리['U0001']} ·  U0003 → {무리['U0003']}")

무리_종류 = set(무리.values())             # 집합으로 만들면 중복이 사라져 종류만 남는다
print(f"이름의 종류 {len(무리_종류)}개 — 이것이 세그먼트 개수입니다.")

이름을 붙인 사람 285명 ·  U0001 → 금융|3 ·  U0003 → 레버리지|4
이름의 종류 15개 — 이것이 세그먼트 개수입니다.

**결과 읽는 법**

- 첫 줄은 무리 이름을 붙인 사람 수와 두 사람의 예입니다.
  - 285명 모두 이름이 붙었습니다.
  - U0001 은 `금융|3`, U0003 은 `레버리지|4` 입니다.
- 둘째 줄의 `15개` 는 서로 다른 무리 이름의 개수입니다.
  - 즉 285명이 세그먼트 15개로 나뉘었습니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2.6 지난주에 못 본 것 — 두 사람이 같은 순위표에서 받았다</mark>

**2.6 에서 하는 일** — 성향이 정반대인 두 사람을 골라, **1주차 방식**으로 추천했을 때 어떤 목록을 받는지 나란히 놓고 몇 자리가 다른지 셉니다.

**1. 왜 지금 이걸 보나**
- 지난 시간 마지막에 보려다 시간이 모자랐던 대목입니다. **오늘 이야기의 출발점이라 먼저 봅니다.**
- 「이걸 추천이라고 부를 수 있나」라는 물음이 오늘 만들 것의 이유입니다.

**2. 어떻게 고르나**
- 채점 구간(마지막 한 달)에 기록이 있는 사람만 고를 수 있습니다. 그런 사람이 **266명**입니다.
- 그중 안정형 한 명(U0001)과 공격형 한 명(U0003)을 뽑습니다.

In [9]:
# 성향이 정반대인 두 사람을 한 명씩 고릅니다.
채점대상 = set(test["user_id"])            # 채점 구간에 기록이 있는 사람만 고를 수 있다
print("채점 구간에 기록이 있는 사람 :", len(채점대상), "명")


def 그_성향의_첫_채점대상(성향):
    """그 성향인 사람들 중 채점 구간에 기록이 있는 첫 사람을 돌려준다."""
    for 사람 in users[users["persona"] == 성향]["user_id"]:   # 그 성향인 사람을 앞에서부터
        if 사람 in 채점대상:                                  # 채점 구간에도 있으면
            return 사람                                       # 그 사람으로 정하고 끝낸다


안정형 = 그_성향의_첫_채점대상("안정형")     # 원금을 지키려는 사람 한 명
공격형 = 그_성향의_첫_채점대상("공격형")     # 위험을 감수하는 사람 한 명
print(f"안정형 → {안정형} ·  공격형 → {공격형}")

# 1주차 방식(모두에게 같은 목록)으로 두 사람에게 추천해 봅니다.
지난주_비교 = pd.DataFrame({                # 두 목록을 나란히 놓은 표를 만든다
    f"안정형 {안정형}": 번호를_이름으로(모두에게_같은_추천(안정형, seen_map[안정형])),   # 번호를 이름으로
    f"공격형 {공격형}": 번호를_이름으로(모두에게_같은_추천(공격형, seen_map[공격형])),
})
지난주_비교.index = range(1, 11)            # 행 이름을 1~10 등수로 바꾼다

print("\n1주차 방식 — 성향이 정반대인 두 사람이 받은 목록\n")
지난주_비교

채점 구간에 기록이 있는 사람 : 266 명
안정형 → U0001 ·  공격형 → U0003

1주차 방식 — 성향이 정반대인 두 사람이 받은 목록

                              안정형 U0001                            공격형 U0003
1   Vanguard FTSE Developed Markets ETF  Vanguard FTSE Developed Markets ETF
2                        TIGER 미국S&P500                 Vanguard S&P 500 ETF
3                  Taiwan Semiconductor                       KODEX 미국나스닥100
4                     Invesco QQQ Trust                       TIGER 리츠부동산인프라
5                  Vanguard S&P 500 ETF        Schwab US Dividend Equity ETF
6                          ACE 미국S&P500                                DB하이텍
7                        KODEX 미국나스닥100                      KODEX 국고채30년액티브
8         Schwab US Dividend Equity ETF                           Salesforce
9                ProShares UltraPro QQQ                  TIGER 은행고배당플러스TOP10
10                                DB하이텍                       KODEX 미국배당다우존스

**결과 읽는 법**

- `266 명` 은 채점 구간(마지막 한 달)에 기록이 있는 사람 수입니다.
- `안정형 → U0001 · 공격형 → U0003` 은 고른 두 사람의 아이디입니다.
  - 각 성향에서 채점 구간에 기록이 있는 첫 사람입니다.
- 아래 표는 1주차 방식으로 두 사람이 받은 추천 10개입니다.
  - 왼쪽 열이 U0001, 오른쪽 열이 U0003 의 목록입니다.
  - 행 번호 1~10 은 추천 순위입니다.

**3. 몇 자리가 다른지 셉니다**

목록이 꽤 달라 보입니다. 그런데 **그것이 두 사람을 다르게 봤다는 뜻은 아닙니다.**

다른 자리 개수와, 자리는 달라도 양쪽에 다 있는 종목 개수를 같이 셉니다.

In [10]:
# 두 목록에서 종목이 다른 자리를 세어 봅니다.
목록_안정 = 모두에게_같은_추천(안정형, seen_map[안정형])   # 안정형이 받은 10개 (번호)
목록_공격 = 모두에게_같은_추천(공격형, seen_map[공격형])   # 공격형이 받은 10개
print("1등끼리 비교 :", name_of[목록_안정[0]], "/", name_of[목록_공격[0]])

다른자리 = []                                  # 자리 번호를 모아 둘 목록
for 자리 in range(10):                         # 1등부터 10등까지
    if 목록_안정[자리] != 목록_공격[자리]:      # 그 자리의 종목이 다르면
        다른자리.append(자리 + 1)              # 사람이 읽는 등수로 담는다

print(f"10자리 중 {len(다른자리)}자리가 다릅니다 — 다른 자리는 {다른자리}")

겹친_종목 = set(목록_안정) & set(목록_공격)     # 자리는 달라도 양쪽에 다 있는 종목
print(f"그런데 종목 자체는 {len(겹친_종목)}개가 겹칩니다 — 자리만 밀린 것입니다.")

print()
print("추천 함수를 다시 보세요. user_id 를 받아 놓고 안에서 한 번도 쓰지 않습니다.")

1등끼리 비교 : Vanguard FTSE Developed Markets ETF / Vanguard FTSE Developed Markets ETF
10자리 중 9자리가 다릅니다 — 다른 자리는 [2, 3, 4, 5, 6, 7, 8, 9, 10]
그런데 종목 자체는 5개가 겹칩니다 — 자리만 밀린 것입니다.

추천 함수를 다시 보세요. user_id 를 받아 놓고 안에서 한 번도 쓰지 않습니다.

**결과 읽는 법**

- `1등끼리 비교` 는 두 사람 목록의 1위 종목입니다.
  - 둘 다 Vanguard FTSE Developed Markets ETF 로 같습니다.
- `9자리가 다릅니다` 는 같은 순위끼리 비교해 종목이 다른 자리의 수입니다.
  - 2위부터 10위까지 9자리입니다.
- `5개가 겹칩니다` 는 순위와 상관없이 두 목록에 모두 들어 있는 종목 수입니다.

**4. 왜 달라 보이나 — 결론**

10자리 중 **9자리가 다르지만**, 종목 자체는 **5개가 겹칩니다.** 자리만 밀린 것입니다.

둘 다 **같은 인기 순위표**에서 위에서부터 받았고, 자리가 밀린 것은 **각자 이미 담은 종목을 뺐기 때문**입니다.

증거는 함수에 있습니다. `모두에게_같은_추천(user_id, seen)` 은 `user_id` 를 받아 놓고 **안에서 한 번도 쓰지 않습니다.** 그 사람이 누구인지 보지 않은 것입니다.

**성향을 한 번도 쓰지 않았습니다.** 이것을 추천이라고 부를 수 있을까요.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2.7 세그먼트별 추천을 만들고 점수를 낸다</mark>

**2.7 에서 하는 일** — 무리마다 인기 순위표를 따로 만들고, 각자 **자기 무리의 순위표**에서 10개를 받게 한 뒤 점수를 냅니다.

**1. 알고리즘은 1주차와 같습니다**
- 「많이 담긴 순으로 10개」 — 새로 배우는 계산법이 없습니다.
- 바뀐 것은 **누구의 거래를 세는가** 하나뿐입니다.

**2. 두 단계**
1. 거래 기록에 무리 이름 열을 붙이고, 무리마다 그 안에서만 세어 **순위표 15개**를 만듭니다.
2. 추천 함수가 그 사람의 무리를 찾아 **그 순위표에서** 아직 안 담은 것 10개를 줍니다.

**3. 무리를 모르는 사람은?** 전체 인기 순위로 돌려 줍니다. 이 문제에는 **콜드 스타트(cold start)** 라는 이름이 있고 3주차에 제대로 다룹니다.

In [11]:
# 거래 기록에 무리 이름을 붙입니다.
거래_무리 = train["user_id"].map(무리)              # 사람 아이디 → 세그먼트 이름
거래_무리포함 = train.assign(group=거래_무리)        # group 열을 더한 새 표
print("group 열이 붙었습니다 :", list(거래_무리포함.columns))

# 무리별로 인기 순위표를 따로 만듭니다.
무리별_순위표 = {}                                  # {세그먼트: 종목 순위 목록}

for 무리이름, 그_무리의_거래 in 거래_무리포함.groupby("group"):   # 세그먼트마다 한 번씩
    그_무리_종목건수 = 그_무리의_거래["item_id"].value_counts()    # 그 안에서만 센다
    무리별_순위표[무리이름] = list(그_무리_종목건수.index)          # 많은 순 번호 목록

print(f"순위표 {len(무리별_순위표)}개를 만들었습니다.")

print()
print("레버리지|4 세그먼트의 상위 3개 :")
for 번호 in 무리별_순위표["레버리지|4"][:3]:        # 그 세그먼트 순위표에서 위 3개만
    print("   ", name_of[번호])

group 열이 붙었습니다 : ['user_id', 'item_id', 'ts', 'event', 'group']
순위표 15개를 만들었습니다.

레버리지|4 세그먼트의 상위 3개 :
    Direxion Semiconductor Bull 3X
    TIGER 미국나스닥100레버리지
    KODEX 코스닥150레버리지

**결과 읽는 법**

- 첫 줄은 새 표의 열 이름입니다.
  - 마지막에 무리 이름을 담은 `group` 열이 붙었습니다.
- `순위표 15개` 는 세그먼트마다 하나씩 만든 인기 순위표의 수입니다.
  - 세그먼트 개수 15개와 같습니다.
- 아래 세 종목은 `레버리지|4` 세그먼트 순위표의 1~3위입니다.
  - 이 세그먼트 사람들의 거래만 세어서 정한 순위입니다.

In [12]:
def 무리별_추천(user_id, seen):
    """그 사람이 속한 세그먼트의 순위표에서 아직 안 담은 것 10개를 준다."""
    그_사람의_무리 = 무리.get(user_id)                       # 세그먼트 이름을 찾는다
    순위표 = 무리별_순위표.get(그_사람의_무리, 인기순위)      # 무리를 모르면 전체 인기순으로
    return recsys.take(순위표, seen)                         # 이미 담은 것을 빼고 10개


print("함수 확인 · U0003 의 1등 :", name_of[무리별_추천("U0003", seen_map["U0003"])[0]])

이번시간_점수, 채점대상_수 = recsys.recall_at_k(무리별_추천, train, test)   # 이번 방식의 Recall@10
print(f"지난 시간 (모두에게 같은 목록)  {지난시간_점수:.4f}")
print(f"이번 시간 (세그먼트별 목록)      {이번시간_점수:.4f}")

오른_비율 = (이번시간_점수 - 지난시간_점수) / 지난시간_점수   # (새 점수 - 옛 점수) ÷ 옛 점수
print(f"\n{오른_비율:+.1%} 올랐습니다.   (채점 대상 {채점대상_수}명)")

함수 확인 · U0003 의 1등 : TIGER 미국나스닥100레버리지
지난 시간 (모두에게 같은 목록)  0.2163
이번 시간 (세그먼트별 목록)      0.2684

+24.1% 올랐습니다.   (채점 대상 266명)

**결과 읽는 법**

- `U0003 의 1등` 은 세그먼트별 추천으로 U0003 이 받은 1위 종목입니다.
  - TIGER 미국나스닥100레버리지 입니다.
- 다음 두 줄은 두 방식의 Recall@10 입니다.
  - 모두에게 같은 목록은 0.2163, 세그먼트별 목록은 0.2684 입니다.
- `+24.1%` 는 지난 시간 점수에 비해 늘어난 비율입니다.
  - (0.2684 − 0.2163) ÷ 0.2163 으로 계산한 값입니다.
  - 채점 대상은 두 방식 모두 266명입니다.

**4. 두 사람을 다시 봅니다**

2.6 에서 비교했던 그 두 사람입니다. 이번에는 두 사람이 **서로 다른 순위표**를 받으므로 근거 자체가 다릅니다.

In [13]:
# 아까 그 두 사람입니다 (위에서 이미 골라 뒀습니다).
print(f"{안정형} 이 속한 세그먼트 : {무리[안정형]}")
print(f"{공격형} 이 속한 세그먼트 : {무리[공격형]}")
print()

비교 = pd.DataFrame({                       # 이번에는 세그먼트별 추천으로 두 목록을 만든다
    f"{안정형} ({무리[안정형]})": 번호를_이름으로(무리별_추천(안정형, seen_map[안정형])),
    f"{공격형} ({무리[공격형]})": 번호를_이름으로(무리별_추천(공격형, seen_map[공격형])),
})
비교.index = range(1, 11)                    # 행 이름을 1~10 등수로

비교

U0001 이 속한 세그먼트 : 금융|3
U0003 이 속한 세그먼트 : 레버리지|4

                           U0001 (금융|3)                       U0003 (레버리지|4)
1                        TIGER 미국배당다우존스                   TIGER 미국나스닥100레버리지
2    iShares 20+ Year Treasury Bond ETF         ProShares UltraPro Short QQQ
3                   TIGER 은행고배당플러스TOP10      iShares Global Clean Energy ETF
4                                  신한지주                                 알테오젠
5                          ACE 미국배당다우존스                             LG에너지솔루션
6                ProShares UltraPro QQQ               Advanced Micro Devices
7        Vanguard Total Bond Market ETF                       TIGER 리츠부동산인프라
8      Vanguard High Dividend Yield ETF  Vanguard FTSE Developed Markets ETF
9                        KODEX 미국배당다우존스                      KODEX 국고채30년액티브
10  Vanguard FTSE Developed Markets ETF                         TIGER 2차전지테마

**결과 읽는 법**

- 첫 두 줄은 두 사람이 속한 세그먼트 이름입니다.
  - U0001 은 `금융|3`, U0003 은 `레버리지|4` 입니다.
- 아래 표는 세그먼트별 추천으로 두 사람이 받은 10개입니다.
  - 열 이름 괄호 안이 그 목록을 만든 세그먼트 순위표입니다.
  - 행 번호 1~10 은 추천 순위입니다.

**5. 결과** — 지난주와 달리 목록이 **성격까지 갈렸습니다.**

`금융|3` 인 U0001 에게는 금융·배당·채권이 위로 오고, `레버리지|4` 인 U0003 에게는 레버리지가 위로 옵니다.

점수는 **0.2163 → 0.2684 (+24.1%)** 입니다.

**❓ 생각해 보기 1**

안정형 U0001(`금융|3`)이 받은 목록 **6위**에 **ProShares UltraPro QQQ**가 있습니다.

이 종목은 이 데이터에서 섹터 `레버리지` · 위험도 `5`인 종목입니다.

세그먼트별 추천은 **왜 안정형 투자자에게 이런 종목을 올렸을까요?**

- 힌트 — 2.7의 순위표가 **무엇을 세어서** 만들어지는지, 그리고 `무리별_추천` 함수 안에 **위험도를 확인하는 줄이 있는지** 보세요.
- 답은 노트북 맨 아래 **「생각해 보기 답」**에 있습니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">2.8 위험도를 빼면 점수가 어떻게 될까</mark>

**2.8 에서 하는 일** — 세그먼트를 **섹터만으로** 나눠 보고, 원래 방식과 점수를 견줍니다.

**1. 무엇을 확인하려는 건가**
- 지금 세그먼트 이름은 **주력 섹터 + 평균 위험도** 두 개로 만들었습니다.
- 그런데 위험도가 정말 필요했을까요. 섹터만으로 나눠도 되지 않을까요.
- **직접 돌려서 점수로 확인합니다.** 이렇게 재료를 하나 빼 보고 점수를 비교하는 것이 실무에서 하는 일입니다.

**2. 무엇이 달라지나** — 이름이 `레버리지|4` 에서 `레버리지` 로 짧아지고, 세그먼트 개수가 **15개에서 9개**로 줄어듭니다.

In [14]:
# 섹터만으로 나눈 세그먼트와 점수를 비교해 봅니다.

def 점수_내보기(무리사전):
    """무리 사전을 받아 세그먼트별 순위표를 만들고 Recall@10 을 돌려준다."""
    거래 = train.assign(group=train["user_id"].map(무리사전))   # 받은 딕셔너리로 group 열을 붙인다

    표 = {}                                                     # {세그먼트: 순위 목록}
    for 이름, 그_거래 in 거래.groupby("group"):                  # 세그먼트마다
        표[이름] = list(그_거래["item_id"].value_counts().index)  # 그 안에서만 세어 순위를 만든다

    def 추천(user_id, seen):
        내_표 = 표.get(무리사전.get(user_id), 인기순위)   # 없으면 전체 인기순
        return recsys.take(내_표, seen)                  # 이미 담은 것을 빼고 10개

    점수, 인원 = recsys.recall_at_k(추천, train, test)   # 점수와 채점 인원 (인원은 안 씀)
    return 점수


# 섹터만으로 만든 무리 딕셔너리 — 위험도를 붙이지 않는다
무리_섹터만 = {}                          # 빈 딕셔너리
for 사람 in 주력섹터:                      # 285명을 돌면서
    무리_섹터만[사람] = 주력섹터[사람]     # 섹터 이름만 그대로 넣는다 (|위험도 없음)

print(f"U0003 의 이름이  {무리['U0003']}  →  {무리_섹터만['U0003']}  으로 짧아졌습니다")
print(f"세그먼트 개수    {len(set(무리.values()))}개  →  {len(set(무리_섹터만.values()))}개")
print()

섹터_위험도_점수 = 점수_내보기(무리)        # 원래 방식 (섹터 + 위험도)
print(f"섹터 + 위험도   Recall@10 = {섹터_위험도_점수:.4f}")

섹터만_점수 = 점수_내보기(무리_섹터만)      # 위험도를 뺀 방식
print(f"섹터만         Recall@10 = {섹터만_점수:.4f}")

print()
print("→ 어느 쪽이 높나요? 세그먼트 개수와 점수는 어떤 관계일까요?")

U0003 의 이름이  레버리지|4  →  레버리지  으로 짧아졌습니다
세그먼트 개수    15개  →  9개

섹터 + 위험도   Recall@10 = 0.2684
섹터만         Recall@10 = 0.2562

→ 어느 쪽이 높나요? 세그먼트 개수와 점수는 어떤 관계일까요?

**결과 읽는 법**

- 첫 두 줄은 위험도를 뺐을 때 바뀐 점입니다.
  - U0003 의 무리 이름이 `레버리지|4` 에서 `레버리지` 로 바뀌었습니다.
  - 세그먼트 개수가 15개에서 9개로 줄었습니다.
- 다음 두 줄은 두 방식의 Recall@10 입니다.
  - 섹터 + 위험도는 0.2684 로, 2.7 에서 낸 점수와 같습니다.
  - 섹터만은 0.2562 입니다.

**3. 생각해 볼 것 — 세그먼트를 잘게 쪼개면 점수가 계속 오를까요?**

섹터만(9개)보다 섹터+위험도(15개)가 점수가 높았습니다. 그러면 더 잘게 쪼갤수록 좋을까요.

**아닙니다.** 한 무리에 사람이 너무 적어지면 그 안에서 세는 거래 건수도 적어져서, 순위표가 **우연에 흔들립니다.** 극단적으로 1인 1무리가 되면 자기가 담은 것만 다시 추천하는 셈이 됩니다.

**잘게 쪼개기와 무리 크기 유지 사이에 적당한 지점**이 있습니다. 그 지점을 데이터로 찾는 것이 뒤 차시에 배울 일입니다.

## <mark style="display:block; background:#ffecb3; color:#1a1a1a; padding:6px 12px; border-radius:4px">3 · 개념 — 채점하는 방법 세 가지  `[PPT]`</mark>

이 파트는 슬라이드로 진행합니다. 노트북은 아래 **4.2** 부터 다시 이어집니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">4.2 세 지표를 한 번에 계산하는 함수</mark>

**4.2 에서 하는 일** — Precision@10 · Recall@10 · NDCG@10 을 한 번에 계산하는 함수를 직접 만듭니다.

**1. 채점 방법**
- 채점 구간의 사람을 **한 명씩** 돌면서 세 지표를 구하고, 마지막에 **평균**을 냅니다.
- **정답 집합** = 그 사람이 마지막 한 달에 담은 것 − 이미 담았던 것. 이미 담은 것을 다시 맞혀도 점수가 아닙니다.
- 맞힐 것이 없는 사람은 채점에서 빼야 합니다. 분모가 0 이 되기 때문입니다.

**2. 세 지표의 차이는 분모입니다**
- **Precision@10** = 맞힌 개수 ÷ **우리가 준 10** — 헛것을 주면 깎입니다.
- **Recall@10** = 맞힌 개수 ÷ **그 사람이 담은 개수** — 놓치면 깎입니다.
- **NDCG@10** = 맞힌 **자리**까지 봅니다. 위에서 맞히면 많이, 아래에서 맞히면 적게 줍니다.

**3. 할인 계수** — NDCG 가 자리마다 깎는 값입니다. 1등 1.000 · 5등 0.387 · 10등 0.289. 아래로 갈수록 완만하게 줄어듭니다. **계산식은 외우지 않습니다.**

In [15]:
K = 10   # 추천 목록의 길이. Precision@10 · Recall@10 의 그 10 입니다.

# NDCG 는 자리마다 점수를 깎습니다. 그 깎는 값이 할인 계수입니다.
# 1등 1.000 · 5등 0.387 · 10등 0.289 — 아래로 갈수록 완만하게 줄어듭니다.
할인 = 1 / np.log2(np.arange(2, K + 2))   # arange(2,12) = 2~11. 로그를 취해 1을 나눈다
print("자리별 할인 계수 :", np.round(할인, 3))   # 1등부터 10등까지. 아래로 갈수록 작아진다


def 세_지표(추천함수, train, test, k=K):
    """Precision@k · Recall@k · NDCG@k 를 한 번에 계산한다."""

    사람별_담은것 = train.groupby("user_id")["item_id"].apply(set).to_dict()   # {사람: 이미 담은 집합}

    precision_모음 = []       # 사람마다의 Precision 을 모아 둘 목록
    recall_모음 = []          # Recall 쪽
    ndcg_모음 = []            # NDCG 쪽

    for 사람, 그_사람의_채점기록 in test.groupby("user_id"):   # 채점 구간의 사람을 한 명씩

        이미_담은것 = 사람별_담은것.get(사람, set())            # 학습 구간에 담은 것
        채점구간_담은것 = set(그_사람의_채점기록["item_id"])    # 마지막 한 달에 담은 것

        # 이미 담은 것은 정답에서 뺍니다
        정답 = 채점구간_담은것 - 이미_담은것                    # 빼기(-) = 차집합

        # 맞힐 것이 없는 사람은 채점에서 제외합니다.
        if len(정답) == 0:
            continue                                          # 다음 사람으로 넘어간다

        추천 = 추천함수(사람, 이미_담은것)[:k]                  # 이 사람에게 준 10개
        맞힌개수 = len(정답 & set(추천))          # 양쪽에 다 있는 것의 개수 (&는 교집합)

        # 분자는 둘 다 맞힌개수 로 같습니다. 분모만 다릅니다.
        #    k 는 우리가 준 개수(10), len(정답) 은 그 사람이 담은 개수입니다.
        precision_분모 = k
        recall_분모 = len(정답)

        precision_모음.append(맞힌개수 / precision_분모)   # 이 사람의 Precision 을 담는다
        recall_모음.append(맞힌개수 / recall_분모)          # 이 사람의 Recall

        # NDCG — 맞힌 자리의 할인 계수를 더한 뒤, 가능한 최댓값으로 나눕니다.
        # (이 대목은 읽고 넘어가시면 됩니다. 자리 가중치를 곱하는 것뿐입니다.)
        얻은점수 = 0.0                            # 맞힌 자리의 가중치를 더해 갈 그릇
        자리 = 0                                  # 지금 몇 번째 자리를 보는지
        for 종목 in 추천:                          # 준 10개를 위에서부터
            if 종목 in 정답:                       # 그 자리에서 맞혔으면
                얻은점수 = 얻은점수 + 할인[자리]    # 그 자리의 가중치를 더한다
            자리 = 자리 + 1                        # 다음 자리로

        최대점수 = 할인[:min(len(정답), k)].sum()   # 위에서부터 다 맞혔을 때의 점수
        ndcg_모음.append(얻은점수 / 최대점수)       # 받은 점수 ÷ 받을 수 있던 최대

    return (float(np.mean(precision_모음)),        # 사람마다의 점수를 평균 낸다
            float(np.mean(recall_모음)),
            float(np.mean(ndcg_모음)))


print("\n세_지표 함수를 만들었습니다 — Precision@10 · Recall@10 · NDCG@10 세 개를 한 번에 돌려줍니다.")

자리별 할인 계수 : [1.    0.631 0.5   0.431 0.387 0.356 0.333 0.315 0.301 0.289]

세_지표 함수를 만들었습니다 — Precision@10 · Recall@10 · NDCG@10 세 개를 한 번에 돌려줍니다.

**결과 읽는 법**

- `자리별 할인 계수` 는 1등부터 10등까지 NDCG 가 쓰는 가중치 10개입니다.
  - 1등은 1, 2등은 0.631, 5등은 0.387, 10등은 0.289 입니다.
  - 맞힌 자리에 해당하는 값이 점수에 더해집니다.
- 마지막 줄은 `세_지표` 함수를 만들었다는 안내입니다.
  - 이 셀은 함수를 만들기만 하고, 점수는 다음 셀에서 계산합니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">4.3 1주차와 2주차를 세 지표로 비교한다</mark>

**4.3 에서 하는 일** — 두 주차 방식을 세 지표로 각각 채점해 한 표에 놓고, 직접 짠 Recall 이 `recsys` 모듈 값과 같은지 **검산**합니다.

검산이 필요한 이유가 있습니다. 지표를 직접 짜면 **정답 집합에서 이미 담은 것을 빼는 것을 잊기 쉽습니다.** 그러면 점수가 부풀려집니다. 이미 값이 나와 있는 Recall 과 맞춰 보면 그 실수를 바로 잡을 수 있습니다.

In [16]:
지난시간_세지표 = 세_지표(모두에게_같은_추천, train, test)   # 1주차 방식을 세 지표로
이번시간_세지표 = 세_지표(무리별_추천, train, test)         # 2주차 방식을 세 지표로

# 직접 짠 Recall 이 recsys 모듈의 값과 같은지 맞춰 봅니다.
직접_계산한_recall = 이번시간_세지표[1]                    # 세 지표 중 둘째가 Recall
if abs(직접_계산한_recall - 이번시간_점수) < 1e-9:        # 아주 작은 차이는 같은 것으로 본다
    print(f"검산 통과 — 직접 계산 {직접_계산한_recall:.4f} = recsys 모듈 {이번시간_점수:.4f}")
else:
    print("값이 다릅니다. 대개 이미 담은 종목을 정답에서 빼지 않은 것이 원인입니다.")

결과 = pd.DataFrame(                                        # 두 줄짜리 표로 만든다
    [지난시간_세지표, 이번시간_세지표],                       # 값 (튜플 두 개)
    columns=["Precision@10", "Recall@10", "NDCG@10"],       # 칸 이름
    index=["1주차 · 모두에게 같은 목록", "2주차 · 세그먼트별 목록"],   # 행 이름
).round(4)                                                  # 소수 네 자리까지

결과

검산 통과 — 직접 계산 0.2684 = recsys 모듈 0.2684

                  Precision@10  Recall@10  NDCG@10
1주차 · 모두에게 같은 목록        0.0793     0.2163   0.1711
2주차 · 세그먼트별 목록          0.0951     0.2684   0.1923

**결과 읽는 법**

- `검산 통과` 는 직접 짠 Recall@10 과 `recsys` 모듈의 Recall@10 이 같다는 뜻입니다.
  - 둘 다 0.2684 입니다.
- 아래 표는 두 방식의 세 지표를 한곳에 놓은 것입니다.
  - 행은 방식(1주차 · 2주차), 열은 지표(Precision@10 · Recall@10 · NDCG@10)입니다.
  - 각 칸은 채점 대상 사람마다 낸 점수의 평균이고, 소수 넷째 자리까지 표시했습니다.

**결과 — 세 지표 모두에서 2주차가 나았습니다.**

| | Precision@10 | Recall@10 | NDCG@10 |
|---|---|---|---|
| 1주차 · 모두에게 같은 목록 | 0.0793 | 0.2163 | 0.1711 |
| 2주차 · 세그먼트별 목록 | **0.0951** | **0.2684** | **0.1923** |

**지표를 바꿔도 결론이 뒤집히지 않았다**는 뜻이므로 이번 개선은 믿을 만합니다.

다만 항상 이렇지는 않습니다. 어떤 모델은 Precision 은 오르는데 Recall 은 떨어지기도 합니다.
그래서 **무엇을 중요하게 여길지 미리 정해 두는 것**이 중요합니다. 이 수업은 **Recall@10** 을 씁니다.

**❓ 생각해 보기 2**

2주차 방식의 Recall@10은 **0.2684**인데, Precision@10은 **0.0951**입니다.

Precision@10만 보면 추천 10개 중 평균 1개도 맞히지 못한 셈입니다.

같은 추천인데 **왜 Precision@10은 이렇게 낮게 나올까요?**

- 힌트 — 4.2의 「세 지표의 차이는 분모입니다」를 보고, 한 사람의 **정답 집합에 보통 몇 개가 들어 있을지** 생각해 보세요.
- 답은 노트북 맨 아래 **「생각해 보기 답」**에 있습니다.

**❓ 생각해 보기 3**

1주차에서 2주차로 오면서 Recall@10은 **+24.1%** 올랐습니다.

그런데 NDCG@10은 0.1711 → 0.1923으로 **+12.4%**만 올랐습니다.

같은 추천을 채점했는데 **왜 NDCG@10은 덜 올랐을까요?**

- 힌트 — 4.2의 할인 계수(1등 1.000 · 5등 0.387 · 10등 0.289)를 보고, **새로 맞힌 종목이 몇 등 자리에 있었을지** 생각해 보세요.
- 답은 노트북 맨 아래 **「생각해 보기 답」**에 있습니다.

In [17]:
# 두 주차 점수를 점수판 파일에 남깁니다. 10주 내내 이 기록과 견줍니다.
recsys.record(1, "모두에게 같은 인기 순위", 지난시간_점수,   # 지난주 방식 — 비교 기준(베이스라인)
              note="알고리즘 없음. 인기 상위 10개를 모두에게 같게 추천했다")

recsys.record(2, "취향이 비슷한 세그먼트끼리", 이번시간_점수,   # 주차 번호 · 방식 이름 · 점수
              note="거래 기록으로 주력 섹터와 평균 위험도를 뽑아 세그먼트로 나눴다")

recsys.leaderboard(upto=2)   # 오늘까지 쌓인 점수판 (뒤 주차는 빼고 본다)

레벨 1 · 모두에게 같은 인기 순위 · Recall@10 = 0.2163
레벨 2 · 취향이 비슷한 세그먼트끼리 · Recall@10 = 0.2684

   level            name  recall_at_10                                 note
0      1   모두에게 같은 인기 순위        0.2163     알고리즘 없음. 인기 상위 10개를 모두에게 같게 추천했다
1      2  취향이 비슷한 세그먼트끼리        0.2684  거래 기록으로 주력 섹터와 평균 위험도를 뽑아 세그먼트로 나눴다

**결과 읽는 법**

- `레벨 1` · `레벨 2` 두 줄은 점수판 파일에 기록한 내용입니다.
  - 레벨 1 은 모두에게 같은 인기 순위로 Recall@10 = 0.2163 입니다.
  - 레벨 2 는 취향이 비슷한 세그먼트끼리로 Recall@10 = 0.2684 입니다.
- 아래 표는 지금까지 쌓인 점수판입니다.
  - `level` 은 주차 번호, `name` 은 방식 이름, `recall_at_10` 은 점수, `note` 는 설명입니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">4.4 오늘의 마무리  `[PPT]`</mark>

거래 기록만 보고 사람을 무리로 나누었더니 점수가 올랐습니다.

성향 설문 같은 것을 따로 받지 않고도 "이 사람이 무엇을 좋아하는지"를 어느 정도 짐작할 수 있다는 뜻입니다.

그런데 아직 한계가 남아 있습니다.

**같은 무리에 속한 사람들은 여전히 똑같은 목록을 받습니다.**

`지수|3` 세그먼트에 89명이 있다면 그 89명은 완전히 같은 추천을 받습니다.

사람마다 다른 추천이 되긴 했지만 무리 단위로만 달라진 것입니다.

그리고 더 신경 쓰이는 것이 하나 있습니다.

우리가 지금까지 재 온 점수가 **정말 믿을 만한 숫자인지** 아직 확인해 보지 않았습니다.

다음 시간에는 모델을 하나도 바꾸지 않고 채점 방법만 다시 들여다봅니다.

그런데 점수가 떨어집니다.

### <mark style="display:block; background:#f8bbd0; color:#1a1a1a; padding:6px 12px; border-radius:4px">생각해 보기 답</mark>

먼저 스스로 답을 생각해 본 뒤에 읽어 보세요. 답에 나오는 숫자는 모두 이 노트북을 실제로 실행해서 얻은 값입니다.

**답 1 — 순위표는 「같은 세그먼트 사람들이 몇 번 담았나」만 세고, 위험도는 확인하지 않기 때문입니다**

- `금융|3` 세그먼트에는 **16명**이 있습니다.
  - 그중 **8명**이 학습 구간에 ProShares UltraPro QQQ를 담았습니다.
  - 그래서 이 세그먼트의 순위표에서 **16위**에 올라 있습니다.
- 16위였던 종목이 U0001의 목록에서는 **6위**가 되었습니다.
  - 순위표 1~15위 중 **10개**를 U0001이 이미 담았기 때문입니다.
  - Bank of America · iShares Core MSCI EAFE ETF · KODEX 국고채30년액티브 등이 이미 담은 종목이라 빠졌습니다.
- 반대쪽에서도 같은 일이 생깁니다.
  - 공격형 U0003(`레버리지|4`)은 9위에 KODEX 국고채30년액티브(위험도 `1`)를 받았습니다.
- 투자자의 성향과 맞지 않는 위험도의 종목을 거르는 방법은 **6주차**에서 다룹니다.
- **한 줄로 정리하면** — 세그먼트별 순위표는 「비슷한 사람이 많이 담은 것」을 줄 뿐이고, 「이 사람에게 맞는 위험도인가」는 따로 확인해야 합니다.

**답 2 — 정답 집합이 작아서, 전부 맞혀도 Precision@10이 높게 나올 수 없기 때문입니다**

- Precision@10의 분모는 **항상 10**입니다.
  - 정답이 3개인 사람은 3개를 모두 맞혀도 3 ÷ 10 = **0.3**입니다.
- 채점 대상 266명의 정답 집합은 평균 **3.7개**, 중앙값(한가운데 값) **3개**입니다.
  - 정답이 1개뿐인 사람도 **48명**입니다.
  - 모든 사람의 정답을 전부 맞혀도 Precision@10 평균은 **0.3665**가 최대입니다.
- 그래서 이 데이터에서는 Precision@10의 크기보다 **방식끼리 비교한 결과**를 봅니다.
  - 1주차 0.0793 → 2주차 0.0951로 올랐다는 것이 의미 있는 정보입니다.
- **한 줄로 정리하면** — Precision@10이 낮은 것은 정답이 적은 데이터의 성질이고, 추천이 나빠서만은 아닙니다.

**답 3 — 더 맞힌 종목이 주로 목록 아래쪽 자리에 있었기 때문입니다**

- 266명 전체에서 맞힌 개수는 **211개 → 253개**로 42개 늘었습니다.
  - 그래서 개수만 세는 Recall@10은 크게 올랐습니다.
- 그런데 자리별로 나눠 보면 다릅니다.
  - 1등 자리에서 맞힌 것은 **49개 → 42개**로 오히려 줄었습니다.
  - 5~10등 자리에서 맞힌 것은 **94개 → 137개**로 늘었습니다.
- NDCG@10은 아래 자리에서 맞힐수록 적게 쳐 줍니다.
  - 10등에서 맞히면 1등에서 맞힌 것의 **0.289**만큼만 점수가 됩니다.
- 실무라면 화면에 위 몇 개만 보이는 서비스일수록 NDCG@10의 변화를 더 눈여겨봅니다.
- **한 줄로 정리하면** — Recall@10은 「몇 개 맞혔나」, NDCG@10은 「몇 등에서 맞혔나」까지 보므로, 두 지표가 오른 폭이 다르면 맞힌 자리가 바뀌었다는 뜻입니다.